import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import PhysicsComponent from "@/Components/Physics";
import Meaning from "@/Components/Meaning";
import Choreography from "@/Components/Choreography";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <Meaning />
        <PhysicsComponent />
        <Choreography />
      </body>
    </html>
  );
}
